name: Component Detection

on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
      - run: dotnet restore MyProject.csproj
      - run: dotnet build MyProject.csproj
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
